# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
export PATH=$PATH:$GOPATH/bin
export GOPATH=$HOME/work

cat <<EOF >/home/vagrant/.bash_profile
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin
export PATH

export PATH=$PATH:$GOPATH/bin
export GOPATH=$HOME/work
export GOBIN=$GOPATH/bin

alias cdtorus="cd $GOPATH/src/github.com/coreos/torus"
EOF

#sudo yum -y update
sudo yum install -y unzip curl wget vim-minimal golang git make docker rkt systemd-container nbd.x86_64 strace lsof psmisc kernel-modules kernel-modules-extra aoetools perf

# use golang 1.8
sudo dnf install fedora-repos-rawhide
sudo dnf --enablerepo=rawhide update golang

# Build and install tours
git clone https://github.com/nak3/torus.git $GOPATH/src/github.com/coreos/torus
cd $GOPATH/src/github.com/coreos/torus
make
./bin/torusctl config -C http://192.168.121.1:2379
sudo ./bin/torusctl config -C http://192.168.121.1:2379

./bin/torusctl completion >  /tmp/torusctl
./bin/torusblk completion >  /tmp/torusblk
./bin/torusd --completion >  /tmp/torusd
sudo cp /tmp/torusctl /usr/share/bash-completion/completions/torusctl
sudo cp /tmp/torusblk /usr/share/bash-completion/completions/torusblk
sudo cp /tmp/torusd /usr/share/bash-completion/completions/torusd

#sudo usermod -d $GOPATH/src/github.com/coreos/torus vagrant

#mkdir -p ~/.vim/bundle
#git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim

# end
SCRIPT

$script_root = <<SCRIPT_ROOT
cat <<EOF >/etc/modules-load.d/nbd.conf
nbd
EOF
cat <<EOF >/etc/modules-load.d/aoe.conf
aoe
EOF
cat <<EOF >/etc/modules-load.d/target_core_user.conf
target_core_user
EOF

systemctl restart systemd-modules-load
systemctl enable systemd-modules-load

IPADDR=`hostname -I | cut -f1 -d' '`
HOSTNAME=`hostname -f`
echo "${IPADDR}	${HOSTNAME}" >> /etc/hosts

yum -y erase vim-minimal
yum -y install sudo vim-enhanced


cd
yum -y install kmod  patch  bash  sh-utils  tar  git bzip2  xz  findutils  gzip  m4  perl  perl-Carp  perl-devel  perl-generators  make  diffutils  gawk gcc  binutils  redhat-rpm-config  hmaccalc net-tools  hostname  bc  elfutils-devel openssl openssl-devel zlib-devel binutils-devel newt-devel python-devel perl bison flex xz-devel pciutils-devel gettext ncurses-devel

yum -y install cmake glib2-devel libnl3-devel glusterfs-api-devel kmod-devel zlib-devel targetcli librbd-devel

cd 
git clone https://github.com/open-iscsi/tcmu-runner.git
cd tcmu-runner
cmake -DSUPPORT_SYSTEMD=ON .
make -j10

cd
git clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
cd linux-stable
make oldconfig
make
sudo make install
sudo make modules_install

# end
SCRIPT_ROOT

Vagrant.configure(2) do |config|
  config.vm.box = "fedora/26-cloud-base"
  config.vm.provision "shell", inline: $script, privileged: false
  config.vm.provision "shell", inline: $script_root, privileged: true
  config.vm.provision "docker" # Just install it

  config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"

  # Increase memory for Parallels Desktop
  config.vm.provider "parallels" do |p, o|
    p.memory = "4096"
  end

  config.vm.provider "libvirt" do |libvirt|
    libvirt.driver = "kvm"
    libvirt.memory = 4096
    libvirt.cpus = 4
  end

  # Increase memory for Virtualbox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  # Increase memory for VMware
  ["vmware_fusion", "vmware_workstation"].each do |p|
    config.vm.provider p do |v|
      v.vmx["memsize"] = "4096"
    end
  end

  config.vm.define :dev2 do | dev2 |
    config.vm.hostname = "dev2"
  end
end
