---
- name: register subscription
  redhat_subscription:
    state: present
    username: "{{ user }}"
    password: "{{ password }}"
    pool: "^Employee SKU$"

- name: disable repo
  command: subscription-manager repos --disable="*"

- name: enable repo
  command: subscription-manager repos --enable={{ item.repo }}
  with_items: "{{ repos }}"
